name = VRE1
description = A simple 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = vre1-layout

; Regions
regions[page_top] = Page top
regions[branding] = Branding
regions[user_first] = User first
regions[user_second] = User second
regions[header] = Header
regions[header_second] = Header second
regions[header_third] = Header third
regions[navigation] = Navigation
regions[navigation_first] = Navigation first
regions[navigation_second] = Navigation second
regions[feature] = Feature
regions[preface_first] = Preface first
regions[preface_second] = Preface second
regions[preface_third] = Preface third
regions[highlight] = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First sidebar
regions[sidebar_second] = Second sidebar
regions[postscript_first] = Postscript first
regions[postscript_second] = Postscript second
regions[postscript_third] = Postscript third
regions[postscript_fourth] = Postscript fourth
regions[footer_first] = Footer first
regions[footer_second] = Footer second
regions[footer_third] = Footer third
regions[footer_fourth] = Footer fourth
regions[footer_fifth] = Footer fifth
regions[subfooter_first] = Subfooter First
regions[subfooter_second] = Subfooter Second
regions[page_bottom] = Page bottom

; Stylesheets
stylesheets[all][] = css/layouts/vre1/vre1.layout.css
